name: Weekly AutoPost

on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Pick a random resource
        id: pick
        run: |
          LINE=$(shuf -n 1 resources.txt)
          echo "RLINE=$LINE" >> $GITHUB_ENV

      - name: Append block to HTML
        run: |
          IFS='|' read -ra PARTS <<< "$RLINE"
          CATEGORY=${PARTS[0]}
          TITLE=${PARTS[1]}
          LINK=${PARTS[2]}

          echo "
          <div class='card'>
            <h2>[${CATEGORY}] ${TITLE}</h2>
            <p>Get the latest resource and boost your prep.</p>
            <a href='${LINK}' class='button'>📥 Join Telegram to Download</a>
          </div>
          " >> index.html

      - name: Commit and push
        run: |
          git config --global user.email "autobot@edudrop.com"
          git config --global user.name "EduDrop Bot"
          git add index.html
          git commit -m "Auto-posted: $RLINE"
          git push
      - name: Post to Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id='@EduDropChannel' \
          -d text='📘 New Study Resource posted! Check it out:\nhttps://yourusername.github.io/edudrop'
